Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x, u, pf, pu = U_fold1D()

fig, ax  = plt.subplots(nrows=2)

ax[0].plot(x,u, lw =3)
ax[0].set_xlabel('$x$')
ax[0].set_ylabel('$U(x)$')

ax[1].plot(x,np.exp(-u), lw=3, color='orange')
ax[1].set_xlabel('$x$')
ax[1].set_ylabel('$p(x)$')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-07e999f69032>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mx[0m[0;34m,[0m [0mu[0m[0;34m,[0m [0mpf[0m[0;34m,[0m [0mpu[0m [0;34m=[0m [0mU_fold1D[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mfig[0m[0;34m,[0m [0max[0m  [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0mnrows[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0max[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mx[0m[0;34m,[0m[0mu[0m[0;34m,[0m [0mlw[0m [0;34m=[0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-1-18118c3ddcb7>[0m in [0;36mU_fold1D[0;34m(ratio, deltaU, T)[0m
[1;32m      7[0m     [0mOUTPUT[0m[0;34m:[0m [0mx[0m [0mcoordinate[0m[0;34m,[0m [0mU[0m[0;34m([0m[0mx[0m[0;34m)[0m [0mpotential[0m[0;34m,[0m [0mpf[0m[0;34m,[0m [0mpu[0m[0;31m"[0m [0mfractions[0m [0mof[0m [0mfolded[0m [0;32mand[0m [0mfunfolded[0m [0mstates[0m [0mrespectively[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m     '''
[0;32m----> 9[0;31m     [0;32massert[0m [0mnp[0m[0;34m.[0m[0many[0m[0;34m([0m[0mT[0m[0;34m)[0m [0;34m>[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m     [0;32massert[0m [0mratio[0m [0;34m<[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m     [0;32massert[0m [0mdeltaU[0m [0;34m>[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

