Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Question: what does this do?
np.array( [ xx**2 for x in range(100) if x%3==0 ])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1833/504933506.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Question: what does this do?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m [0;34m[[0m [0mxx[0m[0;34m**[0m[0;36m2[0m [0;32mfor[0m [0mx[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m100[0m[0;34m)[0m [0;32mif[0m [0mx[0m[0;34m%[0m[0;36m3[0m[0;34m==[0m[0;36m0[0m [0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_1833/504933506.py[0m in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m      1[0m [0;31m# Question: what does this do?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m [0;34m[[0m [0mxx[0m[0;34m**[0m[0;36m2[0m [0;32mfor[0m [0mx[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m100[0m[0;34m)[0m [0;32mif[0m [0mx[0m[0;34m%[0m[0;36m3[0m[0;34m==[0m[0;36m0[0m [0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'xx' is not defined
NameError: name 'xx' is not defined

